langue: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconfig-2-4
cache:
  npm: true
  directories:
    - "~/.cache"
script:
  - eslint 'src/**'
  - npm run test:coveralls
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: clean-reactt
  skip-cleanup: true
notifications:
  email: false